module.exports = {
  overall: {
    index: false,
    favicon: false,
    confirm: false,
    sunduk: false,
    domonet: false,
    sundukDomonet: false,
    lib: false,
  },
  index: {
    price: [],
    https: [],
    style: [],
    fontFamily: [],
    domonet: false,
    buttonSend: false,
    formId: false,
    lang: false,
    lfx: false,
    gtm: false,
    yam: false,
    inputs: [],
    anchors: [],
  },
  sundukIndex: {
    price: [],
    https: [],
    style: [],
    fontFamily: [],
    domonet: false,
    buttonSend: false,
    formId: false,
    lang: false,
    lfx: false,
    gtm: false,
    yam: false,
    inputs: [],
  },
  css: {
    fontFamily: [],
    fontFace: [],
  },
};
